import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Job } from "../types/job";

export default function Home() {
  const [loading, setLoading] = useState(true);
  const [jobs, setJobs] = useState<Job[]>([]);
  const [page, setPage] = useState(1);

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      fetch(`/api/get-jobs?page=${page}&per_page=200`)
        .then((res) => res.json())
        .then((res) => {
          setJobs(res);
        })
        .catch((err) => console.error(err))
        .finally(() => {
          setLoading(false);
        });
    };

    fetchData();
  }, [page]);

  return (
    <>
      <Head>
        <title>Achieve Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ marginBottom: "1rem" }}>
          <button
            disabled={page <= 1}
            onClick={() => setPage((cur) => cur - 1)}
          >
            Prev
          </button>
          <button
            disabled={page >= 2}
            onClick={() => setPage((cur) => cur + 1)}
          >
            Next
          </button>
        </div>
        {loading ? (
          <div>Loading...</div>
        ) : (
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              alignItems: "flex-start",
              gap: "1rem",
            }}
          >
            {jobs.map((job) => (
              <Link
                key={job.id}
                href={
                  job.Country?.toLowerCase().includes("outside")
                    ? `https://careers.achievetestprep.com/jobs/Offshore/${job.id}`
                    : `https://careers.achievetestprep.com/jobs/Careers-inside-USA/${job.id}`
                }
                target="_blank"
              >
                {job.Job_Opening_Name} - {job.Country}
              </Link>
            ))}
          </div>
        )}
      </main>
    </>
  );
}
