import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [loading, setLoading] = useState(true);
  const [jobs, setJobs] = useState([]);
  const [page, setPage] = useState(1);

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      fetch(`/api/get-jobs?page=${page}&per_page=200`)
        .then((res) => res.json())
        .then((res) => {
          setJobs(res);
        })
        .catch((err) => console.error(err))
        .finally(() => {
          setLoading(false);
        });
    };

    fetchData();
  }, [page]);

  return (
    <>
      <Head>
        <title>Achieve Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <button
            disabled={page <= 1}
            onClick={() => setPage((cur) => cur - 1)}
          >
            Prev
          </button>
          <button
            disabled={page >= 2}
            onClick={() => setPage((cur) => cur + 1)}
          >
            Next
          </button>
        </div>
        {loading ? (
          <div>Loading...</div>
        ) : (
          <div>
            {jobs.map((job) => (
              <div key={job.id}>
                {job.Job_Opening_Name} - {job.Number_of_Positions} -{" "}
                {job.Country}
              </div>
            ))}
          </div>
        )}
      </main>
    </>
  );
}
